#ifndef CODA_PCRE_CONFIG_H
#define CODA_PCRE_CONFIG_H

#define LINK_SIZE 2
#define MATCH_LIMIT 10000000
#define MATCH_LIMIT_RECURSION MATCH_LIMIT
#define MAX_NAME_COUNT 10000
#define MAX_NAME_SIZE 32
#define NEWLINE 10
#define PCRE_STATIC
#define POSIX_MALLOC_THRESHOLD 10

#endif
