/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.stcorp.coda;

public interface codacConstants {
  public final static int CODA_MAX_NUM_DIMS = 8;
  public final static int CODA_ERROR_EXPRESSION = (-401);
}
