/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.stcorp.coda;

public class SWIGTYPE_p_coda_expression_struct {
  private transient long swigCPtr;

  protected SWIGTYPE_p_coda_expression_struct(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_coda_expression_struct() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_coda_expression_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_coda_expression_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

