/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.stcorp.coda;

public class SWIGTYPE_p_coda_expression_struct {
  private long swigCPtr;

  protected SWIGTYPE_p_coda_expression_struct(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_coda_expression_struct() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_coda_expression_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

